### PR TITLE
Fix/update dependencies

### PR DESCRIPTION
**Pull request by mikonieminen**

### CODE REVIEW

**Comment by ghost** [comment]
The last commit is not verified

**Comment by mikonieminen** [comment]
> The last commit is not verified

That's because it's a fixup commit that I was about to squash with `379d7e3` once review is otherwise passed.

**Comment by mikonieminen** [comment]
This is now fixed:
- now that the needed fixes are in `rust-sdk`, this depends on `master` branch of it
- all fixup commits are now squashed and all commits signed

**Review by ghost — APPROVED** [review]
All good

**Pull request merged**
