### PR TITLE
Use PosgreSQL as the database

### PR DESCRIPTION
**Pull request by mikonieminen**
Combination of SQLite and Diesel is causing problems with concurrent
database queries and we need to migrate live environments away from it.

This change replaces use of SQLite with PosgreSQL, but doing so is
makes our tests very ugly and unstable.

This is just intermediate change while working towards better solution.

### CODE REVIEW

**Review by joshbenaron — CHANGES_REQUESTED** [review]
Make sure the default db address is localhost:{POSTGRES_PORT}. Currently it's still validator.db (from sqlite)

**Comment by mikonieminen** [comment]
> Make sure the default db address is localhost:{POSTGRES_PORT}. Currently it's still validator.db (from sqlite)

I've removed the defualt value as it does not make sense to have one. Instead the user should provide the `--database-url` CLI argument or use `DATABASE_URL` environment variable.

**Comment by mikonieminen** [comment]
I've also fixed the CI configuration. @joshbenaron is this OK for you now, can you approve?

**Review by joshbenaron — APPROVED** [review]
LGTM

**Pull request merged**
